// <auto-generated />
using System;
using Compiler.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compiler.Persistence.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    [Migration("20220831192228_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Compiler.Domain.Entities.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("Compiler.Domain.Entities.Practice", b =>
                {
                    b.OwnsOne("Compiler.Domain.Entities.ValueObjects.ProjectData", "ProjectData", b1 =>
                        {
                            b1.Property<Guid>("PracticeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MainClassText")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TestClassText")
                                .HasColumnType("TEXT");

                            b1.HasKey("PracticeId");

                            b1.ToTable("Practices");

                            b1.WithOwner()
                                .HasForeignKey("PracticeId");
                        });

                    b.Navigation("ProjectData");
                });
#pragma warning restore 612, 618
        }
    }
}
